[versions]
kotlin = "1.8.22" # https://kotlinlang.org/docs/releases.html#release-details
agp = "8.0.2" # https://developer.android.com/studio/releases/gradle-plugin

compileSdk = "33"
minSdk = "24"
targetSdk = "33"

ktor_version = "2.2.3"

kotlin-datetime = "0.4.0"
kotlin-serialization = "1.5.0-RC"
kotlin-coroutines = "1.6.4"

kotlin-util = "1.8.0"

slf4j = "1.6.1"

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-serialization = {module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization"}
kotlin-datetime = {module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime"}
kotlin-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines"}

kotlin-util = {module = "it.czerwinski:kotlin-util", version.ref = "kotlin-util"}

ktor-serialization = {module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor_version"}

ktor-client-core = {module = "io.ktor:ktor-client-core", version.ref = "ktor_version"}
ktor-client-cio = {module = "io.ktor:ktor-client-cio", version.ref = "ktor_version"}
ktor-client-logging = {module = "io.ktor:ktor-client-logging", version.ref = "ktor_version"}
ktor-client-serialization = {module = "io.ktor:ktor-client-serialization", version.ref = "ktor_version"}
ktor-client-json = {module = "io.ktor:ktor-client-json", version.ref = "ktor_version"}
ktor-client-contentnegotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor_version"}

slf4j = {module = "org.slf4j:slf4j-simple", version.ref = "slf4j"}

test-kotlin = {module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin"}

junit = "junit:junit:4.13.2"