[versions]
kotlin = "1.8.22" # https://kotlinlang.org/docs/releases.html#release-details
agp = "8.0.2" # https://developer.android.com/studio/releases/gradle-plugin

compileSdk = "33"
minSdk = "24"
targetSdk = "33"

ktor_version = "2.2.3"

kotlin-datetime = "0.4.0"
kotlin-serialization = "1.5.0-RC"
kotlin-coroutines = "1.6.4"

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-serialization = {module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization"}
kotlin-datetime = {module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime"}
kotlin-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines"}

test-kotlin = {module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin"}

junit = "junit:junit:4.13.2"